name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install ruff
        run: pip install ruff refurb

      - name: Run ruff check
        run: ruff check .

      - name: Run refurb check
        run: refurb --enable-all .
